version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_ADMIN_USER: {{username_admin}}
      INFLUXDB_ADMIN_PASSWORD: {{password_admin}}
      INFLUXDB_USER: {{username}}
      INFLUXDB_USER_PASSWORD: {{password}}
    volumes:
      - influxdb_data:/var/lib/influxdb
    networks:
      - k6

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - k6

volumes:
  influxdb_data:
  grafana_data:

networks:
  k6:
    driver: bridge